import Foundation

/// Bundled text used only for on-device training / phrase index (no network).
enum ToyCorpus {
    static let lines: [String] = [
        // Swift basics
        "func greet() { print(\"hello\") }",
        "let x = 1 + 2 * 3",
        "var counter = 0",
        "for i in 0..<10 { print(i) }",
        "while counter < 5 { counter += 1 }",
        "repeat { counter -= 1 } while counter > 0",
        "if x > 0 { return true } else { return false }",
        "guard let z = optional else { return }",
        "switch mood { case .happy: break; default: break }",
        "try await load()",
        "throws",
        "rethrows",
        "async let first = fetch()",
        "await MainActor.run { }",
        "Task { await work() }",
        "nonisolated(unsafe)",
        "@MainActor",
        "@Sendable",
        "@escaping",
        "@autoclosure",
        "some View",
        "some Collection",
        "any Equatable",
        "where Element: Hashable",
        "extension String { var trimmed: String { trimmingCharacters(in: .whitespaces) } }",
        "protocol Drawable { func draw() }",
        "struct Point { var x: Double; var y: Double }",
        "enum Mood { case happy, silly, curious }",
        "class Robot { func beep() {} }",
        "final class Cache {}",
        "static let shared = Service()",
        "private(set) var name: String",
        "lazy var engine = Engine()",
        "willSet { }",
        "didSet { }",
        "get { }",
        "set { }",
        "subscript(index: Int) -> Element { get { } set { } }",
        "init(name: String) { self.name = name }",
        "deinit { }",
        "self.",
        "super.init()",
        "required init()",
        "convenience init()",
        "override func viewDidLoad()",
        "import SwiftUI",
        "import Combine",
        "import Foundation",
        "import OSLog",
        "let logger = Logger(subsystem: \"app\", category: \"net\")",
        "ContentView()",
        "VStack(spacing: 8) { }",
        "HStack { }",
        "ZStack { }",
        "NavigationStack { }",
        "List(items) { item in }",
        "ForEach(items, id: \\.id) { }",
        "Button(\"Go\") { }",
        "Text(\"Hello\")",
        "Image(systemName: \"star.fill\")",
        "Label(\"Save\", systemImage: \"tray.and.arrow.down\")",
        ".padding()",
        ".background(.thinMaterial)",
        ".foregroundStyle(.primary)",
        ".font(.headline)",
        ".onAppear { }",
        ".task { }",
        ".onChange(of: value) { _, new in }",
        "@State private var text = \"\"",
        "@Binding var text: String",
        "@ObservedObject var model: Model",
        "@StateObject private var store = Store()",
        "@Environment(\\.dismiss) private var dismiss",
        "@EnvironmentObject var session: Session",
        "ObservableObject",
        "Published",
        "objectWillChange.send()",
        "URLSession.shared.data(from: url)",
        "JSONDecoder().decode(T.self, from: data)",
        "JSONEncoder().encode(value)",
        "Codable",
        "Decodable",
        "Encodable",
        "CodingKeys",
        "enum CodingKeys: String, CodingKey { case id, name }",
        "dictionary[\"key\"] = value",
        "array.map { $0 * 2 }",
        "array.filter { $0 > 0 }",
        "array.reduce(0, +)",
        "array.sorted()",
        "Set(array)",
        "Optional.none",
        "nil",
        "?? \"default\"",
        "as?",
        "as!",
        "is",
        "isEmpty",
        "first",
        "last",
        "count",
        "indices",
        "startIndex",
        "endIndex",
        "String(contentsOf: url)",
        "Data(contentsOf: url)",
        "FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)",
        "// TODO: make this nicer",
        "// FIXME: slow path",
        "// MARK: - Section",
        "/// Doc comment for humans",
        "return",
        "break",
        "continue",
        "fallthrough",
        "inout",
        "mutating func bump()",
        "indirect enum Expr { case number(Int), add(Expr, Expr) }",
        "fatalError(\"unimplemented\")",
        "precondition(index >= 0)",
        "assert(debugCheck())",
    ]
}
